### ISSUE TITLE
Not able to move files

### ISSUE THREAD

**Issue by felipesix** [ume05rw/EzSmb#12]
Hi.
First, thank you very much for this great library, it is very simple to use and it is a time saver.

### Context
I'm trying to move files from UNC to UNC in a windows domain, running my application from a docker Linux container.

### Testing environment
For testing this I have created the following file share on my local host

- \\\\localhost\src
- \\\\localhost\dst

Then I Added 2 .txt files in \\\\localhost\src

### Succeeded
My container was able to read the .txt files from the **src** folder with the following code
```csharp
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var file = await Node.GetNode(@"<ipaddress>\src", "<username>", "<password>");
            var nodes = await file.GetList();
            foreach (var node in nodes)
            {
                Console.WriteLine(node.Name);
            }            
        }
```
### Failed
Although, when trying to use the `Move` method, I don't get any exceptions but the files are not moved as expected
```csharp
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var folder = await Node.GetNode(@"<ipaddress>\src", "<username>", "<password>");
            var nodes = await folder.GetList();
            foreach (var node in nodes)
            {
                _logger.LogInformation($"Moving file {node.Name}");
                await node.Move($@"<ipaddress>\dst\{node.Name}");
            }            
        }
```

Am I doing something wrong? should this code expect to move files from src to dst file share?

**Comment by ume05rw** [comment]
The name of the method may have been misleading.
We have not implemented the ability to move files to another server.

The first argument of the Move method is a relative path, like: "... \anotherFolder\file.txt"

To move a file to another server, use the Read method to get the MemoryStream, Write on the folder node of the other server, and Delete the original node.

**Comment by felipesix** [comment]
Thank you very much for the quick reply, I'm going to try it once I have some time to get back to it, as soon as I can confirm I can do the needful I'll be back to close this.

**Comment by felipesix** [comment]
This worked! thank you

```csharp
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {

            if (stoppingToken.IsCancellationRequested)
            {
                return;
            }

            var source = await Node.GetNode(@"<ip>\src", "<user>", "<password>");
            var sourceFiles = await source.GetList();
            
            var destination = await Node.GetNode(@"<ip>\dst", "<user>", "<password>");
            
            foreach (var file in sourceFiles)
            {
                var stream = await file.Read();
                await destination.Write(stream, file.Name);
                await file.Delete();
            }
            await Task.Delay(5000);
        }
 ```
